raster: 15min
target_col: "h_cm"
horizon_steps_list: [24, 48, 96]
mqtt:
  enabled: false
  host: "localhost"
  port: 1883
  base_topic: "/rivercast"
training_mode: 'per_station'   # 'global' oder 'per_station'
